(in-package #:waller)

(defun check-tile (from to &aux (x (car to))
                                (y (cadr to)))
  (declare (ignorable from))
  (when (tilep x y)
    (when (tilep x y :food)
      (case (tilep x y :food)
        (:A (sfx 3 15))
        (:B (sfx -2 10)))
      (setf (thing-state :hero) (tilep x y :food))
      (tile-rem x y :food))
    T))

(defun check-win ()
  (do-cells (:cell cell :result T)
    (when (tilep$ cell :food)
      (return-from check-win NIL))))

(defun move-hero (direction)
  (unless (eq (tilep$ (thing-cell :hero)
                      (case direction
                        (:up :uwall)
                        (:down :dwall)
                        (:right :rwall)
                        (:left :lwall)))
              (thing-state :hero))
    (case direction
      (:up (move :hero 0 -1 :check-hook #'check-tile))
      (:down (move :hero 0 1 :check-hook #'check-tile))
      (:right (move :hero 1 0 :check-hook #'check-tile))
      (:left (move :hero -1 0 :check-hook #'check-tile)))))
